[[bindings]]
key = "return"
command = "wezterm cli spawn --new-window || open '/Applications/Nix Trampolines/WezTerm.app'"
mods = ["control", "option", "shift"]

[[bindings]]
key = "w"
command = "open '/Applications/Firefox.app'"
mods = ["control", "option", "shift"]

[[bindings]]
key = "j"
command = "yabai -m window --focus south"
mods = ["control", "option", "shift"]

[[bindings]]
key = "k"
command = "yabai -m window --focus north"
mods = ["control", "option", "shift"]

[[bindings]]
key = "h"
command = "yabai -m window --focus west"
mods = ["control", "option", "shift"]

[[bindings]]
key = "l"
command = "yabai -m window --focus east"
mods = ["control", "option", "shift"]
