repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      # - id: no-commit-to-branch
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: check-docstring-first
      - id: check-added-large-files
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua
