background {
  color=rgb(1a1b26)
  path=/nix/store/3a6xm6gs45vrk0mzdrw2acisrgz924s9-gigamoon.jpg
}

general {
  disable_loading_bar=true
  grace=3
  hide_cursor=true
  ignore_empty_input=true
}

input-field {
  check_color=rgb(0db9d7)
  fail_color=rgb(f38ba8)
  font_color=rgb(a9b1d6)
  inner_color=rgb(1a1b26)
  outer_color=rgb(444b6a)
}

label {
  monitor=
  color=rgb(cdd6f4)
  font_family=JetBrainsMono Nerd Font
  font_size=90
  halign=right
  position=-30, 0
  text=$TIME
  valign=top
}

label {
  monitor=
  color=rgb(cdd6f4)
  font_family=JetBrainsMono Nerd Font
  font_size=25
  halign=right
  position=-30, -150
  text=cmd[update:60000] date +"%A, %d %B %Y"
  valign=top
}
