"$schema" = 'https://starship.rs/config-schema.json'

format = """
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
[$directory](fg:#394260 bg:#769ff0)\
[](fg:#769ff0 bg:#394260)\
[$git_branch$git_status](fg:#769ff0 bg:#394260)\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
[ ](fg:#1d2230)\
$fill\
$time
$character"""

[directory]
# style = "fg:#e3e5e5 bg:#769ff0"
format = " $path "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[fill]
symbol = ' '
style = 'bold green'

[git_branch]
symbol = ""
format = ' $symbol $branch '

[git_status]
format = '$all_status '

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%T"
style = "bg:#1d2230"
format = '[[[](fg:#1d2230) $time ](fg:#a0a9cb bg:#1d2230)]($style)'
